// <auto-generated />
namespace BW_Team_5_ClinicaVeterinaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FotoProdotto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FotoProdotto));
        
        string IMigrationMetadata.Id
        {
            get { return "202310191306278_FotoProdotto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
