// <auto-generated />
namespace BW_Team_5_ClinicaVeterinaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeNameOrdinis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeNameOrdinis));
        
        string IMigrationMetadata.Id
        {
            get { return "202310191510221_changeNameOrdinis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
