// <auto-generated />
namespace BW_Team_5_ClinicaVeterinaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Ordinis_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ordinis_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "202310191505018_Ordinis_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
